kpl: prolog.terms.Term.toUnquoted
String prolog.terms.Term.toUnquoted ()
Definition at line 169 of file Term.java.
References prolog.terms.Term.pprint().
Referenced by prolog.io.CharReader.CharReader(), prolog.fluents.StringSink.putElement(), and prolog.terms.Term.toChars().
{
     return pprint();
   }