kpl: prolog.terms.Term.matching_copy
Term prolog.terms.Term.matching_copy (Term that)
Returns a copy of the result if the unification of this and that.
Side effects on this and that are undone using trailing of bindings.. Synchronization happens over this, not over that. Make sure it is used as SHARED.matching_copy(NONSHARED,trail).
Definition at line 101 of file Term.java.
References prolog.terms.Term.copy(), prolog.terms.Term.unify(), and prolog.terms.Trail.unwind().
Referenced by prolog.fluents.DataBase.all0().
{
     Trail trail=new Trail();
     boolean ok=unify(that,trail);
     // if(ok) that=that.copy();
     if(ok)
       that=copy();
     trail.unwind(0);
     return (ok)?that:null;
   }