kpl: prolog.terms.Term.toChars
Nonvar prolog.terms.Term.toChars ()
Definition at line 225 of file Term.java.
References prolog.terms.Term.stringToChars(), and prolog.terms.Term.toUnquoted().
Referenced by prolog.builtins.name_to_chars.exec(), and prolog.io.Parser.getTerm().
{
     return stringToChars(toUnquoted());
   }