kpl: prolog.terms.Term.unify
final boolean prolog.terms.Term.unify (Term that, Trail trail) protected
Dereference and unify_to.
Definition at line 41 of file Term.java.
References prolog.terms.Term.ref(), and prolog.terms.Term.unify_to().
Referenced by prolog.terms.Clause.cnumbervars(), prolog.terms.Term.matches(), prolog.terms.Term.matching_copy(), prolog.terms.Fun.putArg(), prolog.terms.Clause.unfold(), and prolog.terms.Fun.unify_to().
{
     return ref().unify_to(that.ref(),trail);
   }