kpl: prolog.builtins.unfolder_source.exec
int prolog.builtins.unfolder_source.exec (Prog p)
Definition at line 908 of file Builtins.java.
References prolog.terms.Fun.getArg(), prolog.terms.Fun.putArg(), and prolog.terms.Term.toClause().
{
     Clause goal=getArg(0).toClause();
     Prog newp=new Prog(goal,p);
     Unfolder S=new Unfolder(goal,newp);
     return putArg(1,S,p);
   }