kpl: prolog.terms.Clause.appendConj
static final Term prolog.terms.Clause.appendConj (Term x, Term y) static package
Concatenates 2 Conjunctions.
See also
Clause::unfold
Definition at line 257 of file Clause.java.
References prolog.terms.Fun.args, and prolog.terms.Term.ref().
Referenced by prolog.terms.Unfolder.reduceBuiltins(), and prolog.terms.Clause.unfold().
{
     y=y.ref();
     if(x instanceof true_)
       return y;
     if(y instanceof true_)
       return x; // comment out if using getState
     if(x instanceof Conj) {
       Term curr=((Conj)x).args[0].ref();
       Term cont=appendConj(((Conj)x).args[1],y);
       // curr.getState(this,cont);
       return new Conj(curr,cont);
     } else
       return new Conj(x,y);
   }