kpl: prolog.terms.Clause.goalFromString
static Clause prolog.terms.Clause.goalFromString (String line) static
Definition at line 56 of file Clause.java.
References prolog.terms.Const.anEof, prolog.terms.Clause.clauseFromString(), prolog.io.IO.errmes(), prolog.terms.Const.name(), prolog.terms.Clause.toGoal(), and prolog.io.IO.trace().
Referenced by prolog.Init.getGoal().
{
     IO.trace("read string: <"+line+">");
     if(null==line)
       line=Const.anEof.name();
     else if(0==line.length())
       return null;
     Clause C=clauseFromString(line);
     if(null==C) {
       IO.errmes("warning (null Clause):"+line);
       return null;
     }
     // IO.trace("got goal:\n"+C.toGoal()); //OK
     return C.toGoal();
   }