kpl: prolog.terms.Clause.unfold
final Clause prolog.terms.Clause.unfold (Clause that, Trail trail) private
Algebraic composition operation of 2 Clauses, doing the basic resolution step Prolog is based on.
From A0:-A1,A2...An and B0:-B1...Bm it builds (A0:-B1,..Bm,A2,...An) mgu(A1,B0). Note that it returns null if A1 and B0 do not unify.
See also
Term::unify()
Definition at line 282 of file Clause.java.
References prolog.terms.Clause.appendConj(), prolog.terms.Clause.ccopy(), prolog.terms.Clause.Clause(), prolog.terms.Clause.getBody(), prolog.terms.Clause.getFirst(), prolog.terms.Clause.getHead(), prolog.terms.Clause.getRest(), prolog.terms.Term.matches(), and prolog.terms.Term.unify().
Referenced by prolog.terms.Clause.unfold_with_goal().
{
     Clause result=null;
     Term first=getFirst();
     if(first!=null&&that.getHead().matches(first,trail)) {
       that=that.ccopy();
       that.getHead().unify(first,trail);
       Term cont=appendConj(that.getBody(),getRest());
       result=new Clause(getHead(),cont);
     }
     return result;
   }