kpl: prolog.terms.Clause.toGoal
Clause prolog.terms.Clause.toGoal ()
Reads a goal as a clause containing a dummy header with all variables in it.
Definition at line 48 of file Clause.java.
References prolog.terms.Clause.checkIfGround(), prolog.terms.Clause.Clause(), prolog.terms.Clause.dict, prolog.terms.Clause.getHead(), prolog.terms.Clause.pprint(), prolog.io.IO.trace(), and prolog.terms.Term.varsOf().
Referenced by prolog.terms.Clause.goalFromString().
{
     Clause G=new Clause(varsOf(),getHead());
     G.dict=dict;
     G.checkIfGround();
     IO.trace("conversion from clause to goal ignores body of: "+pprint());
     return G;
   }