kpl: prolog.terms.Clause.getRest
final Term prolog.terms.Clause.getRest () package
Gets all but the leftmost goal in the body of a clause, i.e.
from H:-B1,B2,...,Bn it will extract B2,...,Bn. Note that the returned Term is either Conj or True, the last one meaning an empty body.
See also
True
Conj
Definition at line 245 of file Clause.java.
References prolog.terms.Const.aTrue, and prolog.terms.Clause.getBody().
Referenced by prolog.terms.Unfolder.reduceBuiltins(), and prolog.terms.Clause.unfold().
{
     Term body=getBody();
     if(body instanceof Conj)
       return ((Conj)body).args[1].ref();
     else
       return Const.aTrue;
   }