kpl: prolog.terms.Clause.cnumbervars
Clause prolog.terms.Clause.cnumbervars (boolean replaceAnonymous)
Replaces varibles with nice looking upper case constants for printing purposes.
Definition at line 160 of file Clause.java.
References prolog.terms.Clause.Clause(), prolog.terms.Term.numbervars(), prolog.terms.Clause.provenGround(), prolog.terms.Term.unify(), and prolog.terms.Trail.unwind().
Referenced by prolog.Init.evalGoal(), prolog.io.ClauseReader.extract_info(), and prolog.terms.Clause.pprint().
{
     if(dict==null)
       return (Clause)numbervars();
     if(provenGround())
       return this;
     Trail trail=new Trail();
     Iterator e=dict.keySet().iterator();
     while(e.hasNext()) {
       Object X=e.next();
       if(X instanceof String) {
         Var V=(Var)dict.get(X);
         long occNb=((Int)dict.get(V)).longValue();
         String s=(occNb<2&&replaceAnonymous)?"_":(String)X;
         // bug: occNb not accurate when adding artif. '[]' head
         V.unify(new PseudoVar(s),trail);
       }
     }
     Clause NewC=(Clause)numbervars();
     trail.unwind(0);
     return NewC;
   }