kpl: prolog.terms.Clause.checkIfGround
final void prolog.terms.Clause.checkIfGround () package
Detects that a clause is ground (i.e.
has no variables)
Definition at line 77 of file Clause.java.
References prolog.terms.Term.getArity(), prolog.terms.Clause.ground, and prolog.terms.Term.varsOf().
Referenced by prolog.terms.Clause.toGoal().
{
     ground=varsOf().getArity()==0;
   }