kpl: prolog.terms.Clause.ccopy
final Clause prolog.terms.Clause.ccopy () package
Creates a copy of the clause with variables standardized apart, i.e.
something like f(s(X),Y,X) becomes f(s(X1),Y1,X1)) with X1,Y1 variables garantted not to occurring in the the current resolvant.
Definition at line 199 of file Clause.java.
References prolog.terms.Clause.Clause(), prolog.terms.Term.copy(), prolog.terms.Clause.dict, and prolog.terms.Clause.ground.
Referenced by prolog.terms.Unfolder.getAnswer(), prolog.terms.Prog.Prog(), and prolog.terms.Clause.unfold().
{
     if(ground)
       return this;
     Clause C=(Clause)copy();
     C.dict=null;
     C.ground=ground;
     return C;
   }