kpl: prolog.io.ClauseReader.getElement
Term prolog.io.ClauseReader.getElement ()
Definition at line 53 of file ClauseReader.java.
References prolog.terms.Const.anEof, prolog.io.Lexer.atEOF(), prolog.io.ClauseReader.extract_info(), prolog.terms.Clause.getHead(), prolog.io.IO.input, prolog.io.IO.promptln(), prolog.io.Parser.readClause(), prolog.io.CharReader.reader, and prolog.io.ClauseReader.stop().
{
     Clause C=null;
     if(// IO.peer!=null &&
     reader.equals(IO.input)) {
       String s=IO.promptln(">:");
       if(null==s||0==s.length())
         C=null;
       else
         C=new Clause(s);
     } else if(null!=parser) {
       if(parser.atEOF()) {
         C=null;
         stop();
       } else
         C=parser.readClause();
       if(C!=null&&C.getHead().equals(Const.anEof)) {
         C=null;
         stop();
       }
     }
     return extract_info(C);
   }