kpl: prolog.io.IO.print
static final void prolog.io.IO.print (Writer f, String s) static
Definition at line 72 of file IO.java.
References prolog.io.IOPeer.print().
Referenced by prolog.io.IO.print(), prolog.io.IO.println(), prolog.io.IO.promptln(), and prolog.io.ClauseWriter.putElement().
{
     if(!showOutput)
       return;
     if(peer==null) {
       try {
         f.write(s);
         f.flush();
       } catch(IOException e) {
         System.err.println("*** error in printing: "+e);
       }
     } else
       peer.print(s);
     return;
   }