kpl: prolog.io.IO.url_or_file
static final Reader prolog.io.IO.url_or_file (String s) static
Definition at line 239 of file IO.java.
References prolog.io.IO.toReader(), and prolog.io.IO.url2stream().
Referenced by prolog.io.Lexer.Lexer(), prolog.io.CharReader.makeReader(), and prolog.io.IO.toFileReader().
{
     Reader stream=null;
     try {
       if(null==stream)
         stream=url2stream(s,true);
       if(null==stream)
         stream=toReader(new FileInputStream(s));
     } catch(IOException e) {
     }
     return stream;
   }