kpl: prolog.io.IO.errmes
static final void prolog.io.IO.errmes (String s) static
Definition at line 185 of file IO.java.
References prolog.io.IO.getStdOutput(), and prolog.io.IO.println().
Referenced by prolog.fluents.BlackBoard.add(), prolog.io.IO.assertion(), prolog.io.Parser.clsFromString(), prolog.terms.Copier.ConsToVector(), prolog.fluents.Queue.enq(), prolog.io.IO.errmes(), prolog.io.Parser.errorClause(), prolog.builtins.stack_dump.exec(), prolog.builtins.compute.exec(), prolog.builtins.put.exec(), prolog.fluents.DataBase.fromFile(), prolog.terms.Clause.goalFromString(), prolog.io.ClauseReader.make_parser(), prolog.io.IO.printStackTrace(), prolog.io.IO.readln(), prolog.terms.Unfolder.reduceBuiltins(), prolog.Init.run(), prolog.io.Parser.showError(), prolog.fluents.DataBase.streamToProg(), prolog.io.IO.system(), prolog.Init.timeGoal(), prolog.io.IO.toFileWriter(), and prolog.io.IO.url2stream().
{
     if(showErrors)
       println(getStdOutput(),s);
   }