kpl: prolog.io.IO.readln
static final String prolog.io.IO.readln () static
Definition at line 140 of file IO.java.
References prolog.io.IO.getStdInput(), and prolog.io.IOPeer.readln().
Referenced by prolog.io.IO.promptln(), and prolog.io.IO.read_from().
{
     String s;
     if(peer==null) {
       s=readln(getStdInput());
     } else {
       s=peer.readln();
     }
     return s;
   }