kpl: prolog.io.IO.readln
static final String prolog.io.IO.readln (Reader f) static package
Definition at line 125 of file IO.java.
References prolog.io.IO.errmes(), prolog.io.IO.readLine(), and prolog.io.IO.trace().
{
     trace(2,"READLN TRACE: entering");
     String s=null;
     try {
       if(f instanceof BufferedReader) {
         s=((BufferedReader)f).readLine();
       } else
         s=readLine(f);
     } catch(IOException e) {
       errmes("error in readln: e.toString()");
     }
     trace(2,"READLN TRACE:"+"<"+s+">");
     return s;
   }