kpl: prolog.io.IO.toFileWriter
static Writer prolog.io.IO.toFileWriter (String s) static package
Definition at line 52 of file IO.java.
References prolog.io.IO.errmes(), and prolog.io.IO.toWriter().
Referenced by prolog.io.CharWriter.CharWriter().
{
     Writer f=null;
     // mes("HERE"+s);
     try {
       f=toWriter(new FileOutputStream(s));
     } catch(IOException e) {
       errmes("write error, to: "+s);
     }
     return f;
   }