kpl: prolog.Main.init
static int prolog.Main.init () static
Definition at line 9 of file Main.java.
References prolog.Init.askProlog(), prolog.Init.builtinDict, prolog.Init.default_lib, and prolog.Init.startProlog().
Referenced by prolog.Main.main().
{
     if(!Init.startProlog())
       return 0;
     Init.builtinDict=new Builtins();
     Init.askProlog("reconsult('"+Init.default_lib+"')");
     return 1;
   }