kpl: prolog.io.Lexer.next
Term prolog.io.Lexer.next () throws IOException protected
Definition at line 184 of file Parser.java.
References prolog.io.Lexer.char2string(), prolog.io.Lexer.getWord(), prolog.io.Lexer.make_const(), and prolog.io.Lexer.make_number().
Referenced by prolog.io.Parser.getArgs(), prolog.io.Parser.getConjCont(), prolog.io.Parser.getList(), prolog.io.Parser.getListCont(), prolog.io.Parser.getTerm(), prolog.io.Parser.readClause(), and prolog.io.Parser.readClauseOrEOF().
{
     int n=nextToken();
     inClause=true;
     Term T;
     switch(n) {
       case TT_WORD:
         T=getWord(false);
       break;
       case '\'':
         T=getWord(true);
       break;
       case TT_NUMBER:
         T=make_number(nval);
       break;
       case TT_EOF:
         T=new eofToken();
         inClause=false;
       break;
       case TT_EOL:
         T=next();
       break;
       case '-':
         if(TT_NUMBER==nextToken()) {
           T=make_number(-nval);
         } else {
           pushBack();
           T=make_const(char2string(n));
         }
       break;
       case ':':
         if('-'==nextToken()) {
           T=new iffToken(":-");
         } else {
           pushBack();
           T=make_const(char2string(n));
         }
       break;
       case '.':
         int c=nextToken();
         if(TT_EOL==c||TT_EOF==c) {
           inClause=false;
           // dict.clear(); ///!!!: this looses Var names
           T=new eocToken();
         } else {
           pushBack();
           T=make_const(char2string(n)); // !!!: sval is gone
         }
       break;
       case '\"':
         T=new stringToken((constToken)getWord(true));
       break;
       case '(':
         T=new lparToken();
       break;
       case ')':
         T=new rparToken();
       break;
       case '[':
         T=new lbraToken();
       break;
       case ']':
         T=new rbraToken();
       break;
       case '|':
         T=new barToken();
       break;
       case ',':
         T=new commaToken();
       break;
       default:
         T=make_const(char2string(n));
     }
     // IO.mes("TOKEN:"+T);
     return T;
   }