kpl: prolog.io.Lexer.getWord
Term prolog.io.Lexer.getWord (boolean quoted) throws IOException private
Definition at line 145 of file Parser.java.
References prolog.io.Lexer.make_const(), prolog.io.Lexer.make_fun(), and prolog.io.Lexer.make_var().
Referenced by prolog.io.Lexer.next().
{
     Term T;
     if(quoted&&0==sval.length())
       T=make_const("");
     /* DO NOT DO THIS: quoting is meant to prevent it!!!
     else if("()[]|".indexOf(sval.charAt(0))>=0) {
       switch(sval.charAt(0)) {
         case '(':
            T=new lparToken();
           break;
         case ')':
            T=new rparToken();
           break;
         case '[':
            T=new lbraToken();
           break;
         case ']':
            T=new rbraToken();
           break;
         case '|':
            T=new barToken();
           break;
       }
     }
     */
     else {
       char c=sval.charAt(0);
       if(!quoted&&(Character.isUpperCase(c)||'_'==c))
         T=make_var(sval);
       else { // nonvar
         String s=sval;
         int nt=nextToken();
         pushBack();
         T=('('==nt)?make_fun(s):make_const(s);
       }
     }
     return T;
   }