kpl: prolog.fluents.BlackBoard.add
final void prolog.fluents.BlackBoard.add (String k, Term value) protected
Adds a Term or Clause to the the blackboard, to be used by Linda out/1 operation.
See also
PrologBlackBoard
Definition at line 97 of file BlackBoard.java.
References prolog.fluents.Queue.enq(), and prolog.io.IO.errmes().
Referenced by prolog.fluents.BlackBoard.addBack(), and prolog.fluents.DataBase.out().
{
     Queue Q=(Queue)get(k);
     if(Q==null) {
       Q=new Queue();
       put(k,Q);
     }
     if(!Q.enq(value))
       IO.errmes("Queue full, key:"+k);
     // IO.trace("$$Added key/val:"+k+"/"+value+"=>"+this);
   }