kpl: prolog.fluents.BlackBoard.take
final Term prolog.fluents.BlackBoard.take (String k, Term pattern) protected
Removes the first matching Term or Clause from the blackboard, to be used by Linda in/1 operation in PrologBlackBoard.
See also
PrologBlackBoard::in()
Definition at line 72 of file BlackBoard.java.
References prolog.fluents.BlackBoard.addBack(), prolog.terms.Term.matches(), and prolog.fluents.BlackBoard.pick().
Referenced by prolog.fluents.DataBase.cin().
{
     ArrayList V=new ArrayList();
     Term t;
     while(true) {
       t=pick(k);
       if(null==t)
         break;
       // IO.trace("$$After pick: t="+t+this);
       if(t.matches(pattern))
         break;
       else
         V.add(t);
     }
     addBack(k,V);
     return t;
   }