kpl: prolog.terms.Conj.conjToString
String prolog.terms.Conj.conjToString ()
Definition at line 8 of file Conj.java.
References prolog.terms.Fun.args, prolog.terms.Conj.Conj(), prolog.terms.Term.ref(), and prolog.terms.Fun.watchNull().
{
     Term h=args[0].ref();
     Term t=args[1].ref();
     StringBuffer s=new StringBuffer(watchNull(h));
     for(;;) {
       if(!(t instanceof Conj)) {
         s.append(","+t);
         break;
       } else {
         h=((Conj)t).args[0].ref();
         t=((Conj)t).args[1].ref();
         s.append(","+watchNull(h));
       }
     }
     return s.toString();
   }