kpl: prolog.terms.Prog.getElement
Term prolog.terms.Prog.getElement ()
Here is where actual LD-resolution computation happens.
It consists of a chain of "unfolding" steps, possibly involving backtracking, which is managed by the OrStack.
Definition at line 56 of file Prog.java.
References prolog.terms.Unfolder.getAnswer(), prolog.terms.Unfolder.getElement(), prolog.terms.Clause.getHead(), prolog.terms.Unfolder.notLastClause(), prolog.terms.ObjectStack.pop(), prolog.terms.ObjectStack.push(), prolog.terms.Prog.stop(), and prolog.terms.Unfolder.stop().
Referenced by prolog.terms.Prog.ask_engine(), and prolog.terms.Prog.run().
{
     if(null==orStack)
       return null;
     Clause answer=null;
     while(!orStack.isEmpty()) {
       Unfolder I=(Unfolder)orStack.pop();
       answer=I.getAnswer();
       if(null!=answer)
         break;
       Clause nextgoal=I.getElement();
       if(null!=nextgoal) {
         if(I.notLastClause())
           orStack.push(I);
         else
           I.stop();
         if(null==answer)
           orStack.push(new Unfolder(nextgoal,this));
       }
     }
     Term head;
     if(null==answer) {
       head=null;
       stop();
     } else
       head=answer.getHead();
     return head;
   }