kpl: prolog.terms.Prog.stop
void prolog.terms.Prog.stop ()
Definition at line 84 of file Prog.java.
References prolog.terms.Trail.unwind().
Referenced by prolog.Init.evalGoal(), prolog.terms.Prog.firstSolution(), and prolog.terms.Prog.getElement().
                      {
     if(null!=trail) {
       trail.unwind(0);
       trail=null;
     }
     orStack=null;
   }