kpl: prolog.terms.Prog.Prog
prolog.terms.Prog.Prog (Clause goal, Prog parent)
Creates a Prog starting execution with argument "goal".
Definition at line 15 of file Prog.java.
References prolog.terms.Clause.ccopy(), prolog.terms.Prog.orStack, prolog.terms.Prog.parent, prolog.terms.ObjectStack.push(), and prolog.terms.Prog.trail.
Referenced by prolog.terms.Prog.new_engine().
{
     super(parent);
     this.parent=parent;
     goal=goal.ccopy();
     this.trail=new Trail();
     this.orStack=new ObjectStack();
     if(null!=goal)
       orStack.push(new Unfolder(goal,this));
   }