kpl: prolog.builtins.new_fun.exec
int prolog.builtins.new_fun.exec (Prog p)
Definition at line 631 of file Builtins.java.
References prolog.terms.Const.Const(), prolog.terms.Fun.Fun(), prolog.terms.Fun.getArg(), prolog.terms.Fun.getIntArg(), prolog.terms.Fun.init(), prolog.terms.Const.name(), prolog.terms.Fun.putArg(), prolog.builtins.Builtins.toConstBuiltin(), and prolog.builtins.Builtins.toFunBuiltin().
{
     String s=((Const)getArg(0)).name();
     int i=getIntArg(1);
     Term T;
     if(i==0)
       T=Builtins.toConstBuiltin(new Const(s));
     else {
       Fun F=new Fun(s);
       F.init(i);
       T=Builtins.toFunBuiltin(F);
     }
     return putArg(2,T,p);
   }