kpl: prolog.builtins.pred_to_string.exec
int prolog.builtins.pred_to_string.exec (Prog p)
Definition at line 582 of file Builtins.java.
References prolog.terms.Const.Const(), prolog.Init.default_db, prolog.terms.Fun.getArg(), prolog.terms.Term.getKey(), prolog.fluents.DataBase.pred_to_string(), and prolog.terms.Fun.putArg().
{
     String key=getArg(0).getKey();
     String listing=Init.default_db.pred_to_string(key);
     if(null==listing)
       return 0;
     Const R=new Const(listing);
     return putArg(1,R,p);
   }