kpl: prolog.fluents.DataBase.pprint
String prolog.fluents.DataBase.pprint ()
Returns a formatted String representation of this PrologBlackboard object.
Definition at line 131 of file DataBase.java.
References prolog.fluents.HashDict.name(), and prolog.fluents.DataBase.pred_to_string().
Referenced by prolog.builtins.db_to_string.exec(), and prolog.fluents.DataBase.pred_to_string().
{
     StringBuffer s=new StringBuffer(name());
     Iterator e=keySet().iterator();
     while(e.hasNext()) {
       s.append(pred_to_string((String)e.next()));
       s.append("\n");
     }
     return s.toString();
   }