kpl: prolog.fluents.DataBase.addClause
static void prolog.fluents.DataBase.addClause (Clause C, HashDict ktable) static
adds a Clause to the joint Linda and Predicate table
Definition at line 242 of file DataBase.java.
References prolog.Init.default_db, prolog.terms.Clause.getKey(), and prolog.fluents.DataBase.out().
Referenced by prolog.fluents.DataBase.processClause().
{
     String k=C.getKey();
     // overwrites previous definitions
     if(null!=ktable&&null!=ktable.get(k)) {
       ktable.remove(k);
       Init.default_db.remove(k);
     }
     Init.default_db.out(k,C,false);
   }