kpl: prolog.fluents.DataBase.apply_parser
static void prolog.fluents.DataBase.apply_parser (Parser p, String fname, BlackBoard ktable) static private
Definition at line 221 of file DataBase.java.
References prolog.io.Lexer.atEOF(), prolog.io.Parser.isError(), prolog.fluents.DataBase.processClause(), prolog.io.Parser.readClause(), prolog.terms.Clause.setFile(), and prolog.io.Parser.showError().
Referenced by prolog.fluents.DataBase.streamToProg().
{
     for(;;) {
       if(p.atEOF())
         return;
       int begins_at=p.lineno();
       Clause C=p.readClause();
       if(null==C)
         return;
       if(Parser.isError(C))
         Parser.showError(C);
       else {
         // IO.mes("ADDING= "+C.pprint());
         processClause(C,ktable);
         C.setFile(fname,begins_at,p.lineno());
       }
     }
   }