kpl: prolog.fluents.DataBase.pred_to_string
String prolog.fluents.DataBase.pred_to_string (String key)
Definition at line 141 of file DataBase.java.
References prolog.fluents.DataBase.pprint(), and prolog.fluents.Queue.toEnumeration().
Referenced by prolog.builtins.pred_to_string.exec(), and prolog.fluents.DataBase.pprint().
{
     Queue Q=(Queue)get(key);
     if(null==Q)
       return null;
     Iterator e=Q.toEnumeration();
     StringBuffer s=new StringBuffer("% "+key+"\n\n");
     while(e.hasNext()) {
       s.append(((Term)e.next()).pprint());
       s.append(".\n");
     }
     s.append("\n");
     return s.toString();
   }