kpl: prolog.fluents.DataBase.fileToProg
static boolean prolog.fluents.DataBase.fileToProg (String fname, boolean overwrite) static private
Definition at line 191 of file DataBase.java.
References prolog.fluents.DataBase.streamToProg(), and prolog.io.IO.toFileReader().
Referenced by prolog.fluents.DataBase.fromFile().
{
     Reader sname=IO.toFileReader(fname);
     if(null==sname)
       return false;
     return streamToProg(fname,sname,overwrite);
   }