kpl: prolog.fluents.DataBase.all0
void prolog.fluents.DataBase.all0 (int max, ArrayList To, String k, Term FXs) private
Definition at line 64 of file DataBase.java.
References prolog.terms.Term.matching_copy(), and prolog.fluents.Queue.toEnumeration().
Referenced by prolog.fluents.DataBase.all1(), and prolog.fluents.DataBase.all2().
{
     if(0==max)
       max=-1;
     Queue Q=(Queue)get(k);
     if(Q==null)
       return;
     // todo: use always the same "server's" trail
     for(Iterator e=Q.toEnumeration();e.hasNext();) {
       Term t=(Term)e.next();
       if(null==t)
         break;
       t=t.matching_copy(FXs);
       if(t!=null&&0!=max--)
         To.add(t);
     }
   }