kpl: prolog.fluents.DataBase.processClause
static void prolog.fluents.DataBase.processClause (Clause C, HashDict ktable) static
adds a Clause to the joint Linda and Predicate table
See also
Clause
Definition at line 256 of file DataBase.java.
References prolog.fluents.DataBase.addClause(), prolog.terms.Prog.firstSolution(), prolog.terms.Clause.getBody(), prolog.terms.Clause.getHead(), and prolog.terms.Term.matches().
Referenced by prolog.fluents.DataBase.apply_parser().
{
     if(C.getHead().matches(new Const("init"))) {
       // IO.mes("init: "+C.getBody());
       Prog.firstSolution(C.getHead(),C.getBody());
     } else {
       // IO.mes("ADDING= "+C.pprint());
       addClause(C,ktable);
     }
   }