kpl: prolog.terms.Copier.ConsToVector
static ArrayList prolog.terms.Copier.ConsToVector (Const Xs) static
Definition at line 63 of file Copier.java.
References prolog.io.IO.errmes(), and prolog.terms.Fun.getArg().
Referenced by prolog.fluents.ListSource.ListSource(), and prolog.fluents.SourceMerger.SourceMerger().
{
     ArrayList V=new ArrayList();
     Term t=Xs;
     for(;;) {
       if(t instanceof Nil) {
         break;
       } else if(t instanceof Cons) {
         Cons c=(Cons)t;
         V.add(c.getArg(0));
         t=c.getArg(1);
       } else if(t instanceof Const) {
         V.add(t);
         break;
       } else {
         V=null;
         IO.errmes("bad Cons in ConsToVector: "+t);
         break;
       }
     }
     // IO.mes("V="+V);
     return V;
   }