kpl: prolog.io.Parser.getConjCont
final Term prolog.io.Parser.getConjCont (Term curr) throws IOException private
Definition at line 516 of file Parser.java.
References prolog.io.Parser.getTerm(), and prolog.io.Lexer.next().
Referenced by prolog.io.Parser.readClauseOrEOF().
{
     Term n=next();
     Term t=null;
     if(n instanceof eocToken)
       t=curr;
     else if(n instanceof commaToken) {
       Term other=getTerm();
       t=new Conj(curr,getConjCont(other));
     }
     if(null==t) {
       throw new ParserException("'.'","bad body element",n);
     }
     return t;
   }