kpl: prolog.io.Parser.readClause
Clause prolog.io.Parser.readClause ()
Main Parser interface: reads a clause together with variable name information.
catch built exception clauses which are defined in lib.pro - allowing to recover or be quiet about such errors.
Definition at line 406 of file Parser.java.
References prolog.io.Lexer.atEOC(), prolog.io.Lexer.atEOF(), prolog.io.Parser.errorClause(), prolog.io.Lexer.next(), and prolog.io.Parser.readClauseOrEOF().
Referenced by prolog.fluents.DataBase.apply_parser(), prolog.io.Parser.clsFromString(), and prolog.io.ClauseReader.getElement().
{
     Clause t=null;
     boolean verbose=false;
     try {
       t=readClauseOrEOF();
       // IO.mes("GOT Clause:"+t);
     }
     catch(ParserException e) {
       t=errorClause(e,"syntax_error",lineno(),verbose);
       try {
         while(!atEOC()&&!atEOF())
           next();
       } catch(IOException toIgnore) {
       }
     } catch(IOException e) {
       t=errorClause(e,"io_exception",lineno(),verbose);
     } catch(Exception e) {
       t=errorClause(e,"unexpected_syntax_exception",lineno(),true);
     }
     return t;
   }