kpl: prolog.io.Parser.clsFromString
static Clause prolog.io.Parser.clsFromString (String s) static
Definition at line 620 of file Parser.java.
References prolog.terms.Clause.dict, prolog.io.IO.errmes(), prolog.terms.Clause.ground, prolog.io.Parser.Parser(), prolog.io.Parser.patchEOFString(), and prolog.io.Parser.readClause().
Referenced by prolog.terms.Clause.clauseFromString().
{
     if(null==s)
       return null;
     s=patchEOFString(s);
     Clause t=null;
     try {
       Parser p;
       p=new Parser(s);
       t=p.readClause();
     } catch(Exception e) { // nothing expected to catch
       IO.errmes("unexpected parsing error",e);
     }
     if(t.dict==null)
       t.ground=false;
     else
       t.ground=t.dict.isEmpty();
     return t;
   }