kpl: prolog.io.Parser.getTerm
final Term prolog.io.Parser.getTerm (Term n) throws IOException protected
Definition at line 532 of file Parser.java.
References prolog.terms.Fun.args, prolog.io.Parser.getArgs(), prolog.io.Parser.getList(), prolog.terms.Term.toChars(), prolog.builtins.Builtins.toFunBuiltin(), and prolog.terms.Term.token().
{
     Term t=n.token();
     if(n instanceof varToken||n instanceof intToken||n instanceof realToken
         ||n instanceof constToken) {
       // is just OK as it is
     } else if(n instanceof stringToken) {
       t=((Nonvar)((stringToken)n).args[0]).toChars();
       // IO.mes("getTerm:stringToken-->"+t);
     } else if(n instanceof lbraToken) {
       t=getList();
     } else if(n instanceof funToken) {
       Fun f=(Fun)t;
       f.args=getArgs();
       t=Builtins.toFunBuiltin(f);
     } else
       throw new ParserException("var,int,real,constant,'[' or functor",
           "bad term",n);
     return t;
   }