kpl: prolog.io.Parser.readClauseOrEOF
Clause prolog.io.Parser.readClauseOrEOF () throws IOException private
Definition at line 467 of file Parser.java.
References prolog.terms.Clause.dict, prolog.io.Lexer.dict, prolog.io.Parser.getConjCont(), prolog.io.Parser.getTerm(), prolog.io.Lexer.next(), and prolog.io.Parser.toClause().
Referenced by prolog.io.Parser.readClause().
{
     dict=new HashDict();
     Term n=next();
     // IO.mes("readClauseOrEOF 0:"+n);
     if(n instanceof eofToken)
       return null; // $$toClause(n.token(),dict);
     if(n instanceof iffToken) {
       n=next();
       Term t=getTerm(n);
       Term bs=getConjCont(t);
       Clause C=new Clause(new Const("init"),bs);
       C.dict=dict;
       return C;
     }
     Term h=getTerm(n);
     // IO.mes("readClauseOrEOF 1:"+h);
     n=next();
     // IO.mes("readClauseOrEOF 2:"+n);
     if(n instanceof eocToken||n instanceof eofToken)
       return toClause(h,dict);
     // IO.mes("readClauseOrEOF 3:"+b);
     Clause C=null;
     if(n instanceof iffToken) {
       Term t=getTerm();
       Term bs=getConjCont(t);
       C=new Clause(h,bs);
       C.dict=dict;
     } else if(n instanceof commaToken) {
       Term b=getTerm();
       Term bs=getConjCont(b);
       C=toClause(new Conj(h,bs),dict);
     } else {
       throw new ParserException("':-' or '.' or ','","bad body element",n);
     }
     return C;
   }