kpl: prolog.builtins.chars_to_name.exec
int prolog.builtins.chars_to_name.exec (Prog p)
Definition at line 668 of file Builtins.java.
References prolog.terms.Term.charsToString(), prolog.terms.Const.Const(), prolog.terms.Fun.getArg(), prolog.terms.Fun.getIntArg(), and prolog.terms.Fun.putArg().
{
     int convert=getIntArg(0);
     String s=charsToString((Nonvar)getArg(1));
     Nonvar T=new Const(s);
     if(convert>0) {
       try {
         double r=Double.valueOf(s).doubleValue();
         if(Math.floor(r)==r)
           T=new Int((long)r);
         else
           T=new Real(r);
       } catch(NumberFormatException e) {
       }
     }
     return putArg(2,T,p);
   }