kpl: prolog.terms.Fun.getIntArg
final int prolog.terms.Fun.getIntArg (int i)
Definition at line 47 of file Fun.java.
References prolog.terms.Fun.getArg().
Referenced by prolog.builtins.set_max_answers.exec(), prolog.builtins.arg.exec(), prolog.builtins.new_fun.exec(), prolog.builtins.chars_to_name.exec(), and prolog.builtins.set_trace.exec().
{
     return (int)((Int)getArg(i)).getValue();
   }