kpl: prolog.terms.Fun.getArg
final Term prolog.terms.Fun.getArg (int i)
Definition at line 43 of file Fun.java.
References prolog.terms.Term.ref().
Referenced by prolog.terms.Copier.ConsToVector(), prolog.Init.evalGoal(), prolog.builtins.is_builtin.exec(), prolog.builtins.system.exec(), prolog.builtins.file_char_reader.exec(), prolog.builtins.file_clause_reader.exec(), prolog.builtins.char_file_writer.exec(), prolog.builtins.clause_file_writer.exec(), prolog.builtins.get_arity.exec(), prolog.builtins.stack_dump.exec(), prolog.builtins.reconsult.exec(), prolog.builtins.consult.exec(), prolog.builtins.db_add.exec(), prolog.builtins.db_remove.exec(), prolog.builtins.db_collect.exec(), prolog.builtins.db_source.exec(), prolog.builtins.at_key.exec(), prolog.builtins.pred_to_string.exec(), prolog.builtins.arg.exec(), prolog.builtins.new_fun.exec(), prolog.builtins.name_to_chars.exec(), prolog.builtins.chars_to_name.exec(), prolog.builtins.numbervars.exec(), prolog.builtins.compute.exec(), prolog.builtins.source_list.exec(), prolog.builtins.list_source.exec(), prolog.builtins.term_source.exec(), prolog.builtins.integer_source.exec(), prolog.builtins.source_loop.exec(), prolog.builtins.source_term.exec(), prolog.builtins.answer_source.exec(), prolog.builtins.unfolder_source.exec(), prolog.builtins.get.exec(), prolog.builtins.put.exec(), prolog.builtins.stop.exec(), prolog.builtins.split_source.exec(), prolog.builtins.merge_sources.exec(), prolog.builtins.discharge.exec(), prolog.builtins.collect.exec(), prolog.builtins.string_char_reader.exec(), prolog.builtins.string_clause_reader.exec(), prolog.builtins.set_persistent.exec(), prolog.builtins.get_persistent.exec(), prolog.terms.Cons.getHead(), prolog.terms.Fun.getIntArg(), prolog.terms.Cons.getTail(), and prolog.terms.Cons.toString().
{
     return args[i].ref();
   }