kpl: prolog.terms.Fun.unify_to
boolean prolog.terms.Fun.unify_to (Term that, Trail trail) package
Definition at line 113 of file Fun.java.
References prolog.terms.Fun.args, prolog.terms.Term.bind_to(), prolog.terms.Fun.bind_to(), prolog.terms.Fun.Fun(), and prolog.terms.Term.unify().
{
     if(bind_to(that,trail)) {
       Fun other=(Fun)that;
       for(int i=0;i<args.length;i++) {
         if(!args[i].unify(other.args[i],trail))
           return false;
       }
       return true;
     } else
       return that.bind_to(this,trail);
   }