kpl: prolog.terms.Fun.funToString
final String prolog.terms.Fun.funToString () protected
Definition at line 86 of file Fun.java.
References prolog.terms.Const.qname(), and prolog.terms.Fun.show_args().
Referenced by prolog.terms.Conj.toString(), and prolog.terms.Fun.toString().
{
     if(args==null)
       return qname()+"()";
     int l=args.length;
     return qname()+(l<=0?"":"("+show_args()+")");
   }