kpl: prolog.terms.Fun.listify
Const prolog.terms.Fun.listify ()
Definition at line 168 of file Fun.java.
References prolog.terms.Const.aNil, prolog.terms.Fun.args, prolog.terms.Const.Const(), and prolog.terms.Const.name().
Referenced by prolog.fluents.DataBase.all1().
{
     Cons l=new Cons(new Const(name()),Const.aNil);
     Cons curr=l;
     for(int i=0;i<args.length;i++) {
       Cons tail=new Cons(args[i],Const.aNil);
       curr.args[1]=tail;
       curr=tail;
     }
     return l;
   }