kpl: prolog.terms.Fun.funClone
final Fun prolog.terms.Fun.funClone ()
Definition at line 133 of file Fun.java.
References prolog.terms.Fun.Fun().
Referenced by prolog.terms.Fun.initializedClone(), prolog.terms.Fun.reaction(), prolog.builtins.Builtins.toFunBuiltin(), and prolog.terms.Fun.unInitializedClone().
{
     Fun f=null;
     try {
       // use of clone is needed for "polymorphic" copy
       f=(Fun)clone();
     } catch(CloneNotSupportedException e) {
       // IO.errmes("clone: "+e);
     }
     return f;
   }