kpl: prolog.terms.Fun.putArg
final int prolog.terms.Fun.putArg (int i, Term T, Prog p)
Definition at line 55 of file Fun.java.
References prolog.terms.Prog.getTrail(), and prolog.terms.Term.unify().
Referenced by prolog.builtins.file_char_reader.exec(), prolog.builtins.file_clause_reader.exec(), prolog.builtins.char_file_writer.exec(), prolog.builtins.clause_file_writer.exec(), prolog.builtins.get_stdin.exec(), prolog.builtins.get_stdout.exec(), prolog.builtins.get_arity.exec(), prolog.builtins.ctime.exec(), prolog.builtins.get_default_db.exec(), prolog.builtins.new_db.exec(), prolog.builtins.db_remove.exec(), prolog.builtins.db_collect.exec(), prolog.builtins.db_source.exec(), prolog.builtins.at_key.exec(), prolog.builtins.pred_to_string.exec(), prolog.builtins.db_to_string.exec(), prolog.builtins.arg.exec(), prolog.builtins.new_fun.exec(), prolog.builtins.name_to_chars.exec(), prolog.builtins.chars_to_name.exec(), prolog.builtins.numbervars.exec(), prolog.builtins.compute.exec(), prolog.builtins.source_list.exec(), prolog.builtins.list_source.exec(), prolog.builtins.term_source.exec(), prolog.builtins.integer_source.exec(), prolog.builtins.source_loop.exec(), prolog.builtins.source_term.exec(), prolog.builtins.answer_source.exec(), prolog.builtins.unfolder_source.exec(), prolog.builtins.get.exec(), prolog.builtins.split_source.exec(), prolog.builtins.merge_sources.exec(), prolog.builtins.collect.exec(), prolog.builtins.term_string_collector.exec(), prolog.builtins.term_collector.exec(), prolog.builtins.string_char_reader.exec(), prolog.builtins.string_clause_reader.exec(), and prolog.builtins.get_persistent.exec().
{
     // return getArg(i).unify(T,p.getTrail())?1:0;
     return args[i].unify(T,p.getTrail())?1:0;
   }