kpl: prolog.terms.Unfolder.Unfolder
prolog.terms.Unfolder.Unfolder (Clause g, Prog p)
Creates an Unfolder based on goal clause g for resolution step in program p.
Iterator e is set to range over matching clauses in the database of program p.
Definition at line 34 of file Unfolder.java.
References prolog.Init.default_db, prolog.terms.Clause.getFirst(), prolog.terms.Term.getKey(), prolog.terms.Prog.getTrail(), prolog.terms.Unfolder.reduceBuiltins(), prolog.fluents.DataBase.toEnumerationFor(), prolog.terms.Unfolder.trace_failing(), prolog.terms.Unfolder.trace_goal(), and prolog.terms.Unfolder.trace_nomatch().
{
     super(p);
     this.goal=g;
     this.prog=p;
     this.e=null;
     trace_goal(g);
     reduceBuiltins();
     if(null!=goal) {
       Term first=goal.getFirst();
       if(null!=first) {
         oldtop=prog.getTrail().size();
         this.e=Init.default_db.toEnumerationFor(first.getKey());
         if(!e.hasNext())
           trace_nomatch(first);
       }
     } else
       trace_failing(g);
   }