kpl: prolog.terms.Unfolder.getElement
Clause prolog.terms.Unfolder.getElement ()
Returns a new clause by unfolding the goal with a matching clause in the database, or null if no such clause exists.
Definition at line 120 of file Unfolder.java.
References prolog.terms.Prog.getTrail(), prolog.terms.Term.toClause(), prolog.terms.Clause.unfold_with_goal(), and prolog.terms.Trail.unwind().
Referenced by prolog.terms.Prog.getElement().
{
     if(null==e)
       return null;
     Clause unfolded_goal=null;
     while(e.hasNext()) {
       Term T=(Term)e.next();
       if(!(T instanceof Clause))
         continue;
       // resolution step, over goal/resolvent of the form:
       // Answer:-G1,G2,...,Gn.
       prog.getTrail().unwind(oldtop);
       // unify() happens here !!!
       unfolded_goal=T.toClause().unfold_with_goal(goal,prog.getTrail());
       if(null!=unfolded_goal)
         break;
     }
     return unfolded_goal;
   }