kpl: prolog.terms.Unfolder.trace_goal
final void prolog.terms.Unfolder.trace_goal (Clause g) package
Tracer on entering g.
Definition at line 149 of file Unfolder.java.
References prolog.terms.Clause.getFirst(), prolog.terms.Clause.pprint(), prolog.io.IO.println(), and prolog.terms.Prog.tracing.
Referenced by prolog.terms.Unfolder.Unfolder().
{
     switch(Prog.tracing) {
       case 2:
         IO.println(">>>: "+g.getFirst());
       break;
       case 3:
         IO.println(">>>: "+g.pprint());
       break;
     }
   }