kpl: prolog.terms.Unfolder.reduceBuiltins
final void prolog.terms.Unfolder.reduceBuiltins () package
Reduces builtin functions after the neck of a clause, before a "real" atom is unfolded.
Definition at line 80 of file Unfolder.java.
References prolog.terms.Clause.appendConj(), prolog.io.IO.errmes(), prolog.terms.Term.exec(), prolog.terms.Clause.getFirst(), prolog.terms.Clause.getHead(), and prolog.terms.Clause.getRest().
Referenced by prolog.terms.Unfolder.Unfolder().
{
     for(;;) {
       Term first=goal.getFirst();
       if(null==first)
         break; // cannot reduce further
       if(first instanceof Conj) { // advances to next (possibly) inline builtin
         goal=new Clause(goal.getHead(),Clause.appendConj(first,goal.getRest()));
         first=goal.getFirst();
       }
       int ok=first.exec(prog); // (possibly) executes builtin
       switch(ok) {
         case -1: // nothing to do, this is not a builtin
         break;
         case 1: // builtin suceeds
           // IO.mes("advancing: "+goal);
           goal=new Clause(goal.getHead(),goal.getRest());
           continue; // advance
         case 0: // builtin fails
           goal=null;
         break; // get out
         default: // unexpected code: programming error
           IO.errmes("Bad return code:"+ok+") in builtin: "+first);
           goal=null;
         break;
       }
       // IO.mes("leaving reduceBuiltins: "+goal);
       break; // leaves loop
     }
   }