kpl: prolog.terms.Cons.toString
String prolog.terms.Cons.toString ()
List printer.
Definition at line 29 of file Cons.java.
References prolog.terms.Cons.Cons(), prolog.terms.Fun.getArg(), and prolog.terms.Fun.watchNull().
{
     Term h=getArg(0);
     Term t=getArg(1);
     StringBuffer s=new StringBuffer("["+watchNull(h));
     for(;;) {
       if(t instanceof Nil) {
         s.append("]");
         break;
       } else if(t instanceof Cons) {
         h=((Cons)t).getArg(0);
         t=((Cons)t).getArg(1);
         s.append(","+watchNull(h));
       } else {
         s.append("|"+watchNull(t)+"]");
         break;
       }
     }
     return s.toString();
   }