kpl: prolog.builtins.Builtins.toFunBuiltin
static Fun prolog.builtins.Builtins.toFunBuiltin (Fun f) static
Definition at line 177 of file Builtins.java.
References prolog.terms.Fun.args, prolog.Init.builtinDict, prolog.terms.Fun.funClone(), prolog.terms.Fun.getArity(), prolog.terms.Const.name(), and prolog.builtins.Builtins.newBuiltin().
Referenced by prolog.builtins.new_fun.exec(), prolog.builtins.source_term.exec(), and prolog.io.Parser.getTerm().
{
     if(f.name().equals(":-")&&f.getArity()==2) {
       return new Clause(f.args[0],f.args[1]);
     }
     if(f.name().equals(",")&&f.getArity()==2) {
       return new Conj(f.args[0],f.args[1]);
     }
     FunBuiltin B=(FunBuiltin)Init.builtinDict.newBuiltin(f);
     if(null==B)
       return f;
     B=(FunBuiltin)B.funClone();
     B.args=f.args;
     return B;
   }