kpl: prolog.io.ClauseWriter.putElement
int prolog.io.ClauseWriter.putElement (Term t)
Definition at line 20 of file ClauseWriter.java.
References prolog.terms.Term.charsToString(), prolog.terms.SystemObject.name(), prolog.terms.Term.pprint(), prolog.io.IO.print(), and prolog.io.CharWriter.writer.
{
     if(null==writer)
       return 0;
     String s=null;
     if((t instanceof Fun)&&"$string".equals(((Fun)t).name())) {
       Const Xs=(Const)((Fun)t).getArg(0);
       s=Term.charsToString(Xs);
     } else
       s=t.pprint();
     IO.print(writer,s);
     return 1;
   }