kpl: prolog.builtins.compute.exec
int prolog.builtins.compute.exec (Prog p)
Definition at line 710 of file Builtins.java.
References prolog.terms.Const.Const(), prolog.io.IO.errmes(), prolog.terms.Fun.getArg(), prolog.terms.Fun.putArg(), and prolog.terms.SystemObject.toString().
{
     Term o=getArg(0);
     Term a=getArg(1);
     Term b=getArg(2);
     if(!(o instanceof Const)||!(a instanceof Num)||!(b instanceof Num))
       IO.errmes("bad arithmetic operation ("+o+"): "+a+","+b+"\nprog: "
           +p.toString());
     String opname=((Const)o).name();
     double x=((Num)a).getValue();
     double y=((Num)b).getValue();
     double r;
     char op=opname.charAt(0);
     switch(op) {
       case '+':
         r=x+y;
       break;
       case '-':
         r=x-y;
       break;
       case '*':
         r=x*y;
       break;
       case '/':
         r=x/y;
       break;
       case ':':
         r=(int)(x/y);
       break;
       case '%':
         r=x%y;
       break;
       case '?':
         r=(x<y)?(-1):(x==y?0:1);
       break; // compares!
       case 'p':
         r=Math.pow(x,y);
       break;
       case 'l':
         r=Math.log(y)/Math.log(x);
       break;
       case 'r':
         r=x*Math.random()+y;
       break;
       case '<':
         r=(long)x<<(long)y;
       break;
       case '>':
         r=(long)x>>(long)y;
       break;
       default:
         IO.errmes("bad arithmetic operation <"+op+"> on "+x+" and "+y);
         return 0;
     }
     Num R=((Math.floor(r)==r))?(Num)(new Int((long)r)):(Num)(new Real(r));
     return putArg(3,R,p);
   }