kpl: prolog.fluents.Queue.toVector
ArrayList prolog.fluents.Queue.toVector ()
Definition at line 133 of file Queue.java.
References prolog.fluents.Queue.inc(), and prolog.fluents.Queue.tail.
Referenced by prolog.fluents.Queue.toEnumeration(), prolog.fluents.BlackBoard.toEnumerationFor(), and prolog.fluents.Queue.toString().
{
     // enterCritical(); DEADLOCKS!
     ArrayList v=new ArrayList();
     for(int i=head;i!=tail;i=inc(i))
       v.add(queue[i]);
     // exitCritical();
     return v;
   }