kpl: prolog.fluents.Queue.requeue
final boolean prolog.fluents.Queue.requeue (String Mes) private
Dynamically resizes the queue.
Definition at line 54 of file Queue.java.
References prolog.fluents.Queue.count(), prolog.fluents.Queue.inc(), prolog.fluents.Queue.tail, prolog.fluents.Queue.toString(), and prolog.io.IO.trace().
Referenced by prolog.fluents.Queue.deq(), and prolog.fluents.Queue.enq().
{
     int newSize=2*count();
     if(newSize>MAX_QUEUE||newSize<MIN_QUEUE)
       return false;
     IO.trace(Mes+"!!! "+toString());
     Object[] nqueue=new Object[newSize];
     int j=0;
     for(int i=head;i!=tail;i=inc(i))
       nqueue[j++]=queue[i];
     queue=nqueue;
     head=0;
     tail=j;
     return true;
   }