kpl: prolog.fluents.Queue.enq
final boolean prolog.fluents.Queue.enq (Object V)
Adds an element to the end of the queue.
Definition at line 89 of file Queue.java.
References prolog.io.IO.errmes(), prolog.fluents.Queue.inc(), prolog.fluents.Queue.requeue(), and prolog.fluents.Queue.tail.
Referenced by prolog.fluents.BlackBoard.add(), prolog.fluents.SourceMerger.getElement(), and prolog.fluents.Queue.Queue().
{
     // enterCritical();
     if(inc(tail)==head) { // full !!!
       if(!requeue("expanding")) {
         IO.errmes("Warning: queue overflow at:"+V);
         return false;
       }
     }
     queue[tail]=V;
     tail=inc(tail);
     // exitCritical();
     return true;
   }