kpl: prolog.fluents.Queue.deq
final Object prolog.fluents.Queue.deq ()
Removes the first element of the queue.
Definition at line 107 of file Queue.java.
References prolog.fluents.Queue.count(), prolog.fluents.Queue.head, prolog.fluents.Queue.inc(), and prolog.fluents.Queue.requeue().
Referenced by prolog.fluents.SourceMerger.getElement(), and prolog.fluents.BlackBoard.pick().
{
     // enterCritical();
     if(tail==head) // empty !!!
       return null;
     if(4*count()<queue.length)
       requeue("shrinking");
     Object V=queue[head];
     head=inc(head);
     // exitCritical();
     return V;
   }