kpl: prolog.terms.Trail.unwind
final void prolog.terms.Trail.unwind (int to)
Used to undo bindings after unification, if we intend to leave no side effects.
Definition at line 33 of file Trail.java.
References prolog.terms.ObjectStack.pop(), and prolog.terms.Term.undo().
Referenced by prolog.terms.Clause.cnumbervars(), prolog.terms.Unfolder.getElement(), prolog.terms.Term.matches(), prolog.terms.Term.matching_copy(), and prolog.terms.Prog.stop().
{
     // IO.mes("unwind TRAIL: "+name()+": "+size()+"=>"+to);
     // if(to>size())
     // IO.assertion("unwind attempted from smaller to larger top");
     for(int i=size()-to;i>0;i--) {
       Term V=(Term)(pop());
       V.undo();
     }
   }