kpl: prolog.Init.evalGoal
static void prolog.Init.evalGoal (Clause Goal) static
evalutes a query
Definition at line 52 of file Init.java.
References prolog.terms.Const.aNo, prolog.terms.Prog.ask_engine(), prolog.terms.Const.aYes, prolog.terms.Clause.cnumbervars(), prolog.terms.Prog.firstSolution(), prolog.terms.Fun.getArg(), prolog.terms.Term.getArity(), prolog.terms.Clause.getBody(), prolog.terms.Clause.getHead(), prolog.Init.moreAnswers(), prolog.terms.Term.numbervars(), prolog.io.IO.println(), and prolog.terms.Prog.stop().
Referenced by prolog.Init.timeGoal().
{
     Clause NamedGoal=Goal.cnumbervars(false);
     Term Names=NamedGoal.getHead();
     if(!(Names instanceof Fun)) { // no vars in Goal
       Term Result=Prog.firstSolution(Goal.getHead(),Goal.getBody());
       if(!Const.aNo.equals(Result))
         Result=Const.aYes;
       IO.println(Result.toString());
       return;
     }
     Prog E=new Prog(Goal,null);
     for(int i=0;;i++) {
       Term R=Prog.ask_engine(E);
       // IO.mes("GOAL:"+Goal+"\nANSWER: "+R);
       if(R==null) {
         IO.println("no");
         break;
       }
       if(Names instanceof Fun) {
         Fun NamedR=(Fun)R.numbervars();
         for(int j=0;j<Names.getArity();j++) {
           IO.println(((Fun)Names).getArg(j)+"="+NamedR.getArg(j));
         }
         // IO.println(";");
         if(!moreAnswers(i)) {
           E.stop();
           break;
         }
       }
     }
   }