kpl: prolog.Init.moreAnswers
static boolean prolog.Init.moreAnswers (int i) static package
Definition at line 86 of file Init.java.
References prolog.io.IO.maxAnswers, prolog.io.IO.println(), and prolog.io.IO.promptln().
Referenced by prolog.Init.evalGoal().
{
     if(IO.maxAnswers==0) { // under user control
       String more=IO.promptln("; for more, <enter> to stop: ");
       return more.equals(";");
     } else if(i<IO.maxAnswers||IO.maxAnswers<0) {
       IO.println(";"); // print all remaining
       return true;
     } else { // i >= ...}
       IO.println(";");
       IO.println("No more answers computed, max reached! ("+IO.maxAnswers+")");
       return false;
     }
   }