kpl: prolog.terms.Const.name
final String prolog.terms.Const.name ()
Definition at line 31 of file Const.java.
References prolog.terms.Const.sym.
Referenced by prolog.builtins.system.exec(), prolog.builtins.file_clause_reader.exec(), prolog.builtins.char_file_writer.exec(), prolog.builtins.clause_file_writer.exec(), prolog.builtins.reconsult.exec(), prolog.builtins.consult.exec(), prolog.builtins.arg.exec(), prolog.builtins.new_fun.exec(), prolog.terms.Clause.goalFromString(), prolog.terms.Fun.isClause(), prolog.terms.Fun.listify(), prolog.builtins.Builtins.newBuiltin(), prolog.builtins.Builtins.toConstBuiltin(), prolog.terms.Copier.toFun(), prolog.builtins.Builtins.toFunBuiltin(), prolog.terms.PseudoVar.toString(), prolog.terms.Const.toUnquoted(), and prolog.terms.Copier.VectorToFun().
{
     return sym;
   }