kpl: prolog.terms.Const.Const
prolog.terms.Const.Const (String s)
Definition at line 27 of file Const.java.
Referenced by prolog.terms.Const.bind_to(), prolog.io.constToken.constToken(), prolog.io.eocToken.eocToken(), prolog.builtins.system.exec(), prolog.builtins.file_char_reader.exec(), prolog.builtins.file_clause_reader.exec(), prolog.builtins.char_file_writer.exec(), prolog.builtins.clause_file_writer.exec(), prolog.builtins.reconsult.exec(), prolog.builtins.consult.exec(), prolog.builtins.pred_to_string.exec(), prolog.builtins.db_to_string.exec(), prolog.builtins.arg.exec(), prolog.builtins.new_fun.exec(), prolog.builtins.chars_to_name.exec(), prolog.builtins.compute.exec(), prolog.builtins.merge_sources.exec(), prolog.builtins.set_persistent.exec(), prolog.io.iffToken.iffToken(), and prolog.terms.Fun.listify().
{
     sym=s.intern();
   }